apiVersion: apps/v1
kind: Deployment
metadata:
  name: abdel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice
  template:
    metadata:
      labels:
        app: myservice
    spec:
      containers:
        - image: 123456/my-service:tagname
          imagePullPolicy: IfNotPresent
          name: abdel
      restartPolicy: Always
